language: python
python: 2.7
sudo: false
cache:
  pip: true
  directories:
    - eggs
    - downloads
env:
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1
install:
  - sed -ie "s#travis-5.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - pip install --upgrade pip setuptools zc.buildout
  - buildout -qNc travis.cfg buildout:download-cache=downloads
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v
script: bin/test
